### ISSUE TITLE
Invalid argument supplied ...

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/custom_pub#2]
After activating the module:

![retbw4](https://cloud.githubusercontent.com/assets/13515302/14063632/eeab622c-f3e2-11e5-96e5-45200a562033.png)

**Comment by ghost** [comment]
Thanks for the report, this issue is not easy to reproduce (it depends on caching conditions).
Fixed anyway in [2c9e488](https://github.com/backdrop-contrib/custom_pub/commit/2c9e4884e7356ec63eca85547dcbc8d343b6db78).
